name: pocket_codex
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.5.0-143.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  get: ^4.6.6
  cached_network_image: ^3.3.1
  logger: ^2.3.0
  flutter_skeleton_ui: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

