name: pocket_codex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.5.0-143.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  get: ^4.6.6
  cached_network_image: ^3.3.1
  logger: ^2.3.0
  flutter_skeleton_ui: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/

